### ISSUE TITLE
`./node_modules/.bin/catalog build` throws 

### ISSUE THREAD

**Issue by safareli** [interactivethings/catalog#408] opened 2018-04-20 17:08 UTC
```
$ ./node_modules/.bin/catalog build
/myproject/node_modules/args/lib/utils.js:317
      throw err;
      ^

Error: spawn catalog-build ENOENT
    at exports._errnoException (util.js:1020:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:197:32)
    at onErrorNT (internal/child_process.js:376:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:496:3
```

**Comment by herrstucki** [comment] 2018-04-20 18:18
This seems to be related to https://github.com/interactivethings/catalog/issues/343. Upgrading Catalog to a newer version should fix your problem.

**Comment by safareli** [comment] 2018-04-24 16:42
I'm on recent version:

```
$  ./node_modules/.bin/catalog -v
3.5.2
$ ./node_modules/.bin/catalog start
/Users/safareli/myproject/node_modules/args/lib/utils.js:317
      throw err;
      ^

Error: spawn catalog-start ENOENT
    at exports._errnoException (util.js:1020:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:197:32)
    at onErrorNT (internal/child_process.js:376:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:496:3

```


While:
```
$ npm start

> @ start /Users/safareli/myproject
> catalog start


  Starting Catalog …
```

**Comment by herrstucki** [comment] 2018-04-25 19:12
This seems to be a limitation of the `args` module which executes scripts from package.json instead of the subcommand files directly. When you run `catalog start` as an npm script, it works correctly because in the `npm run` context the scripts from package.json are available but otherwise not. I'm not sure what we can do to fix this other than document the issue somehow.

For reference: https://github.com/leo/args/issues/69, https://github.com/leo/args/issues/83

**Comment by herrstucki** [comment] 2018-05-19 14:07
@safareli I'm closing this since there doesn't seem anything we can do about it at the moment. Feel free to ping me when the issue is resolved in `args`. Thanks!

**Closed by herrstucki** 2018-05-19 14:07 UTC
